apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-redis
  ports:
    - name: redis
      port: {{ .Values.redis.port | int }}
      targetPort: {{ .Values.redis.port | int }}
