apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-cache
  labels:
    {{- include "homeport-api.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.agentCache.accessMode }}
  storageClassName: {{ .Values.agentCache.storageClass }}
  resources:
    requests:
      storage: {{ .Values.agentCache.size }}
