{{- if not .Values.secrets.existingSecret }}
# Secret géré par Helm uniquement si aucun existingSecret n'est fourni.
# En production : utiliser sealed-secrets / external-secrets / Rancher.
apiVersion: v1
kind: Secret
metadata:
  name: homeport-secrets
  labels:
    {{- include "homeport-api.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $k, $v := .Values.secrets.values }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
