import {
  Globe,
  BarChart3,
  PenTool,
  Users,
  Brain,
  BookOpen,
  Terminal,
  GitBranch,
  Eye,
  Mic,
  Microscope,
  LineChart,
  Network,
  ShieldCheck,
  Shield,
  Scale,
  Rocket,
  Lock,
  Key,
  Zap,
  Mail,
  ClipboardList,
  Settings,
  Bot,
  Sparkles,
  Send,
  CheckCircle2,
  Clock,
  CreditCard,
  Building2,
  Briefcase,
  FlaskConical,
  CircleCheck,
  Database,
  TrendingUp,
  Layers,
  Cpu,
  ArrowRight,
  FileText,
  Code2,
  ScanText,
  Play,
  Save,
  ChevronRight,
  ChevronLeft,
  Maximize2,
  Minimize2,
  HelpCircle,
  Home,
  Check,
} from "lucide-react";

const ICONS: Record<string, any> = {
  tim: Globe,
  ada: BarChart3,
  donald: PenTool,
  denis: Users,
  van: Brain,
  hypatie: BookOpen,
  alan: Terminal,
  rene: GitBranch,
  hedy: Eye,
  graham: Mic,
  marie: Microscope,
  florence: LineChart,
  isaac: Network,
  claude: ShieldCheck,
  shield: Shield,
  scale: Scale,
  rocket: Rocket,
  lock: Lock,
  key: Key,
  zap: Zap,
  mail: Mail,
  clipboard: ClipboardList,
  settings: Settings,
  bot: Bot,
  sparkles: Sparkles,
  send: Send,
  check: Check,
  circleCheck: CircleCheck,
  check2: CheckCircle2,
  clock: Clock,
  creditCard: CreditCard,
  building: Building2,
  briefcase: Briefcase,
  flask: FlaskConical,
  database: Database,
  trendingUp: TrendingUp,
  layers: Layers,
  cpu: Cpu,
  arrowRight: ArrowRight,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  file: FileText,
  code: Code2,
  scan: ScanText,
  play: Play,
  save: Save,
  maximize: Maximize2,
  minimize: Minimize2,
  help: HelpCircle,
  home: Home,
};

export type IconName = keyof typeof ICONS;

export const Icon: React.FC<{
  name: IconName;
  size?: number;
  color?: string;
  strokeWidth?: number;
  className?: string;
}> = ({ name, size = 20, color = "currentColor", strokeWidth = 2, className }) => {
  const Component = ICONS[name];
  if (!Component) return null;
  return (
    <Component size={size} color={color} strokeWidth={strokeWidth} className={className} />
  );
};
