apiVersion: v2
name: kinn
version: 1.0.16
appVersion: v0.0.35
description: "Super logiciel d'automatisation"
annotations:
  catalog.cattle.io/display-name: "Kinn"
  catalog.cattle.io/dependencies: "mongodb"
icon: https://kinn.fr/kinn-logo.png
maintainers:
  - name: Edouard Bernier
    email: edouard.bernier@i55.fr
