openapi: 3.0.3
info:
  title: Kinn Backend API
  version: 0.1.0
  description: |
    Swagger spec (initial) covering Auth, Company/Workspaces, Providers, Node Templates,
    Credentials, Flows, Runs, and Webhooks. JWT Bearer required for /api/*.
servers:
  - url: https://api.example.com
security:
  - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /auth/login:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: { type: string }
                password: { type: string }
              required: [email, password]
            example: { email: "demo@example.com", password: "demo" }
      responses:
        '200': { description: OK }
